spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${MYSQL_ID}
    password: ${MYSQL_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver   # 보통 생략해도 자동 감지됨
  jpa:
    hibernate:
      ddl-auto: update           # 필요에 따라 create / validate 등
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
